name: Deploy to the Live channel

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build-and-deploy-production:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PNpM (Fast, disk space efficient package manager)
        run: npm i -g pnpm@latest

      - name: Install dependencies
        run: pnpm i

      - name: Build webapp
        run: pnpm build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./website
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: filledstacks-blog
          channelId: live